# Generated by Django 6.0 on 2025-12-12 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_feedback_trip_booking_delete_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
