# Generated by Django 6.0 on 2025-12-13 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_booking_from_city_booking_to_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='from_city',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='to_city',
        ),
        migrations.AddField(
            model_name='booking',
            name='persons',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='trip',
            name='date_end',
            field=models.DateField(default='2025-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='date_start',
            field=models.DateField(default='2025-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='travel_date',
            field=models.DateField(default='2025-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='users.trip'),
        ),
    ]
