# Generated by Django 6.0 on 2025-12-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_booking_from_city_remove_booking_to_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='date_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='date_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
