# Generated by Django 6.0 on 2025-12-13 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_trip_date_end_alter_trip_date_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='travel_date',
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='trip',
            name='date_end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='date_start',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='trips/'),
        ),
    ]
