# Generated by Django 6.0 on 2025-12-14 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_offer_trip_alter_offer_discount_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='discount_percent',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='offer',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='users.trip'),
        ),
    ]
