# Generated by Django 6.0 on 2025-12-14 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_offer_discount_percent_alter_offer_trip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='trip',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='users.trip'),
            preserve_default=False,
        ),
    ]
